version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/document_management
      - SECRET_KEY=dev_key_change_in_production
      - ENCRYPTION_KEY=dev_encryption_key_change_in_prod
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
    ports:
      - "5000:5000"

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=document_management
    
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data: